spring:
  application:
    name:
      api-gateway

zuul:
    prefix: /api
    routes:
      customer-service:
        path: /customer-service/**
        url: https://ims-customer-service.herokuapp.com/

      order-service:
        path: /order-service/**
        url: https://ims-order-service.herokuapp.com/

      product-service:
        path: /product-service/**
        url: https://ims-product-service.herokuapp.com/

      user-service:
        path: /user-service/**
        url: https://ims-user-service.herokuapp.com/
        stripPrefix : false
        sensitiveHeaders : Cookie,Set-Cookie

      db-service:
        path: /db-service/**
        url: https://ims-db-service.herokuapp.com/
