spring:
  application:
    name:
      api-gateway

zuul:
    prefix: /api
    routes:
      customer-service:
        path: /customer-service/**
        url: http://localhost:8302/

      order-service:
        path: /order-service/**
        url: http://localhost:8303/

      product-service:
        path: /product-service/**
        url: http://localhost:8304/

      user-service:
        path: /user-service/**
        url: http://localhost:8305/

      db-service:
        path: /db-service/**
        url: http://localhost:8306/
